# Generated by Django 2.2.4 on 2020-05-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.FileField(upload_to=''),
        ),
    ]
