# Generated by Django 2.2.4 on 2020-05-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20200516_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_img',
            new_name='book_image',
        ),
    ]
